#!/usr/bin/env python
# desenvolvido por manoel vitor
# data 10/12/2022
# main.py

from mp3Tube import MP3Download
from mp4Tube import MP4Download
from sys import argv
from os import *

if __name__ == "__main__":
	try:

		opc = str(argv[1])
		url = str(argv[2])
		param = str(argv[3])

		if opc == "-audio": # baixar arquivo mp3
			instance = MP3Download(url)
			print("Downloading file mp3...")
			instance.init()
		elif opc == '-video': # baixar arquivo mp4
			instance = MP4Download(url)
			print("Downloading file mp4")
			instance.getDownload()
		elif opc == '-paudio': # baixar playlist mp3
			print('Dont still finished.')
	
	except ValueError:
		print('===================================================')
		print('./main <type> <url>')
		print(' By manoel vitor')
		print(' DESCRIPTION COMMAND:')
		print('===================================================')
		print('./main.py -audio <url_youtube_video> - download mp3')
		print('./main.py -video <url_youtube_video> - download mp4')
		print('===================================================')

